apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  labels:
    app: feedback-app
spec:
  type: NodePort
  selector:
    app: feedback-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080